### ISSUE TITLE
"CHM13_chr8_chr21.bam" is an incorrect file

### ISSUE THREAD

**Issue by Zhiliang-Zhang** [EichlerLab/CDR-Finder#7]
Hello,

Thanks for developing an useful tool! But, I noticed that "CHM13_chr8_chr21.bam" is an incorrect file when running test data.
Please send me a correct BAM file. 
<img width="408" alt="image" src="https://github.com/user-attachments/assets/033c808d-29e6-4c71-9ab2-b7344d71fef5" />

Thank you very much!

Best
zzl

**Comment by koisland** [comment]
Hi @Zhiliang-Zhang,

This might be because the test files are stored with [`git lfs`](https://git-lfs.com/). Did you run the commands in the README?
```
git lfs install && git lfs pull
```

Thanks,
Keith

**Comment by Zhiliang-Zhang** [comment]
> Hi @Zhiliang-Zhang,
> 
> This might be because the test files are stored with [`git lfs`](https://git-lfs.com/). Did you run the commands in the README?
> 
> ```
> git lfs install && git lfs pull
> ```
> 
> Thanks, Keith

Thanks!
Zhiliang
